import {Nunito} from "next/font/google"
import './globals.css'
import Navbar from  "./components/Navbar/Navbar"
import ClientOnly from "./components/ClientOnly";
// import Modal from "./components/modals/Modal";
import RegisterModal from "./components/modals/RegisterModal";
import ToasterProvider from "./providers/ToasterProvider";
import LoginModal from "./components/modals/LoginModal";
import getCurrentuser from "./actions/getCurrentUser";
import RentModal from "./components/modals/RentModal";
const font = Nunito({
  subsets: ["latin"],
});
export const metadata = {
  title: 'Retro Bookings',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
  
}) {
  const currentUser = await getCurrentuser();
  return (
    <html lang="en">
      <body className={font.className}>
        <ClientOnly>
          <ToasterProvider />
          <RegisterModal />
          <LoginModal />
          <RentModal />
          {/* <Modal actionLabel="Submit" title="Hello World" isOpen/> */}
         <Navbar currentUser = {currentUser} />
        </ClientOnly>
        {children}
        </body>
    </html>
  )
}
